name: Auto Assign

on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - reopened

env:
  GH_TOKEN: ${{ github.token }}
  MEMBERS: |
    HaradaTakayuki
    kazutan1230
    Marukome0743
    tanePON

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Select a Assignee
        run: |
          echo $MEMBERS |
            tail -n +2 |
            shuf -n 1 |
            xargs echo "ASSIGNEE=" | tr -d ' ' >> $GITHUB_ENV
          echo "Assignee: ${{ env.ASSIGNEE }}"

      - name: Assign Issue
        if: github.event_name == 'issues' && toJSON(github.event.issue.assignees) == '[]'
        run: gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ env.ASSIGNEE }} --repo ${{ github.repository }}

      - name: Assign Pull Request
        if: github.event_name == 'pull_request' && toJSON(github.event.pull_request.assignees) == '[]'
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ env.ASSIGNEE }} --repo ${{ github.repository }}
