name: Auto Assign Issue

on:
  issues:
    types: opened

jobs:
  random-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Random Member
        if: ${{ toJSON(github.event.issue.assignees) == '[]' }}
        env:
          NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEMBERS: |
            HaradaTakayuki
            kazutan1230
            Marukome0743
            tanePON
        run: |
          echo "$MEMBERS" |
            tail -n +2 |
            shuf -n 1 |
            xargs gh issue edit $NUMBER --add-assignee
