name: Pull Request Labeler

on:
- pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-24.04

    steps:
    - name: Labeling
      uses: actions/labeler@v5
