name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openup-labtakizawa'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if the release has already been created
        run: |
          if gh release view "$VERSION" >/dev/null 2>&1; then
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create release
        if: env.RELEASE_EXISTS != 'true'
        run: gh release create "$VERSION" --generate-notes -t "$REPO_NAME $VERSION"
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_NAME: ${{ github.event.repository.name }}
          VERSION: ${{ github.event.inputs.version || github.ref_name }}
