name: Release

on:
  push:
    branches: main
    paths:
      - "package.json"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check version diff on package.json
        run: |
          echo "VERSION=$(git diff HEAD^ HEAD package.json | grep '^+.\+version' | \
          grep -oE '([0-9]+\.){1}[0-9]+(\.[0-9]+)?')" >> $GITHUB_ENV

      - name: Create release
        if: ${{ env.VERSION != '' }}
        run: gh release create $VERSION --generate-notes -t "$REPO_NAME $VERSION"
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_NAME: ${{ github.event.repository.name }}
