name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openup-labtakizawa'

    steps:
      - name: Create release
        run: gh release create $VERSION --generate-notes -t "$REPO_NAME $VERSION"
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_NAME: ${{ github.event.repository.name }}
          VERSION: ${{ github.ref_name }}
